
let
    Source = Csv.Document(
        File.Contents("C:\Path\To\Sample_-_Superstore.csv"),
        [Delimiter=",", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.Csv]
    ),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),

    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
        {"Row ID", Int64.Type},
        {"Order ID", type text},
        {"Order Date", type date},
        {"Ship Date", type date},
        {"Ship Mode", type text},
        {"Customer ID", type text},
        {"Customer Name", type text},
        {"Segment", type text},
        {"Country", type text},
        {"City", type text},
        {"State", type text},
        {"Postal Code", type text},
        {"Region", type text},
        {"Product ID", type text},
        {"Category", type text},
        {"Sub-Category", type text},
        {"Product Name", type text},
        {"Sales", type number},
        {"Quantity", Int64.Type},
        {"Discount", type number},
        {"Profit", type number}
    }),

    // Verification step — dataset already has zero duplicate rows,
    // kept here for documentation / repeatability.
    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Row ID"}),

    #"Added Month Name" = Table.AddColumn(
        #"Removed Duplicates", "Order Month", each Date.MonthName([Order Date]), type text
    ),
    #"Added Month Number" = Table.AddColumn(
        #"Added Month Name", "Order Month No", each Date.Month([Order Date]), Int64.Type
    ),
    #"Added Year" = Table.AddColumn(
        #"Added Month Number", "Order Year", each Date.Year([Order Date]), Int64.Type
    ),

    #"Reordered Columns" = Table.ReorderColumns(#"Added Year", {
        "Row ID", "Order ID", "Order Date", "Order Year", "Order Month", "Order Month No",
        "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country",
        "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category",
        "Product Name", "Sales", "Quantity", "Discount", "Profit"
    })
in
    #"Reordered Columns"

